kind: stack

description: Starlit CLI tool stack

depends:
- sysext/starlit-cli-fish.bst
- sysext/starlit-cli-bat.bst
- sysext/starlit-cli-eza.bst
- sysext/starlit-cli-atuin.bst
- sysext/starlit-cli-chezmoi.bst
- sysext/starlit-cli-dysk.bst
- sysext/starlit-cli-fd.bst
- sysext/starlit-cli-gh.bst
- sysext/starlit-cli-ripgrep.bst
- sysext/starlit-cli-starship.bst
- sysext/starlit-cli-zoxide.bst
- sysext/starlit-cli-mise.bst
- sysext/starlit-cli-usage.bst
- sysext/starlit-cli-fnox.bst
